apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dbpwd
  namespace: final
spec:
  encryptedData:
    dbpwd: AgB2H+FA/4uVv+wpmrj1gbo5DZJ2Cp3obhZ71wlQkK8n5xjYqsW6R9djaLgp6vy6rexAVpzd97sIyuBwdm+AlQnWzsD3uURWXCy5h8eE/yr2hsJ9H3pEo+AaIUviQXkkesgXbnQRTGRK3rPpiKSDzgYMFksqRz4Pp+d/BTfOOZz/cxS+aHMbKVJo1qBvwLUITvrvSQxWgBVJ5PDAt9m/AiumMdcvkTnHP0qmh13BaSkCgOTZe5ZK22i8XwgIBtPYPaYKOuugxdTMAwTt4AwPr/IQBaUa4NnY9tKYHVwtML+MLG4D+l5N1eBwJoR1cceiyQ0NoiON3+JP+3SQcMMCGYXZ2h0j2Ew0W2/2b0Hd6emlHhjC8wVpohu0DSaj1lPFD6YQLtHOr6ZFGjH9Ild3wjtIZzo5EGFPFOPnqf8Ds9GNKzt5oU5Nbl+OQTbGYvJFVNulR25IbdGM3xABJOr+3UPCavZKP9YSMEJ5eiMnaaCpVJsh6LvS7DBXbPG1puj2OaRlQbyvqCoiWj0TY5ryLx6PWRsItfh5xQ0JAF6mD/R2ubBhC7WOmsw6YoXSOdvD+9GjWhqO4yzGplamDqCHMJQIXoF43rylM+/bUvpz9QftNHntg1Vqd3BKL5i8MepLRT0cKz911mUTZpXnJbQANVQ9wmAZh6Zkksk2WexhSlfq4p7W+4se/laW/KeYHvfenfZya0T5aaN7aw==
  template:
    metadata:
      creationTimestamp: null
      name: dbpwd
      namespace: final

