apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.deployname}}-lb"
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "colors-app.selectorLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "colors-app.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.lbservice.port }}
      targetPort: {{ .Values.lbservice.targetPort }}
  type: {{ .Values.lbservice.type }}