# Manual update 4
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployname }}
  namespace: {{ .Values.namespace }}
  labels:
    infra: frontend
    app: employees
    env: prod
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "colors-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "colors-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.apprepo.name }}:{{ .Values.apprepo.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: {{ .Values.appservice.name }}
          containerPort: {{ .Values.appservice.port }}
          protocol: TCP
        env:
        - name: DBHOST
          value: {{ .Values.env.dbhost | quote }}
        - name: DBPORT
          value: {{ .Values.env.dbport | quote }}
        - name: DBUSER
          valueFrom:
            configMapKeyRef:
              name: webappinfo
              key: dbuser
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: dbpwd
              key: dbpwd
        - name: BGIMAGE
          valueFrom:
            configMapKeyRef:
              name: webappinfo
              key: bgimage
        - name: OURNAMES
          valueFrom:
            configMapKeyRef:
              name: webappinfo
              key: ournames
      imagePullSecrets:
      - name: ecr-cred          