apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: colorsapp-be
  namespace: final
spec:
  interval: 1m
  url: https://github.com/KSBolton/flux-wk13-manifest
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: colorsdb
  namespace: final
spec:
  interval: 1m
  releaseName: colorsdb
  chart:
    spec:
      chart: charts/colors-db
      reconcileStrategy: Revision      
      sourceRef:
        kind: GitRepository
        name: colorsapp-be